#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.296
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataModelLib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Medallia")]
	public partial class MedalliaDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Inserttbdata_medallia(tbdata_medallia instance);
    partial void Updatetbdata_medallia(tbdata_medallia instance);
    partial void Deletetbdata_medallia(tbdata_medallia instance);
    partial void InsertTBDAT(TBDAT instance);
    partial void UpdateTBDAT(TBDAT instance);
    partial void DeleteTBDAT(TBDAT instance);
    partial void InserttbISO(tbISO instance);
    partial void UpdatetbISO(tbISO instance);
    partial void DeletetbISO(tbISO instance);
    #endregion
		
		public MedalliaDataContext() : 
				base(global::DataModelLib.Properties.Settings.Default.MedalliaConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MedalliaDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedalliaDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedalliaDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MedalliaDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<tbdata_medallia> tbdata_medallias
		{
			get
			{
				return this.GetTable<tbdata_medallia>();
			}
		}
		
		public System.Data.Linq.Table<TBDAT> TBDATs
		{
			get
			{
				return this.GetTable<TBDAT>();
			}
		}
		
		public System.Data.Linq.Table<tbISO> tbISOs
		{
			get
			{
				return this.GetTable<tbISO>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbdata_medallia")]
	public partial class tbdata_medallia : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private short _DataID;
		
		private System.Nullable<System.DateTime> _DataDate;
		
		private string _HotelCode;
		
		private System.Nullable<int> _alldata;
		
		private System.Nullable<int> _Hv_email;
		
		private System.Nullable<int> _Not_email;
		
		private System.Nullable<int> _Hv_add1;
		
		private System.Nullable<System.DateTime> _Medallia;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDataIDChanging(short value);
    partial void OnDataIDChanged();
    partial void OnDataDateChanging(System.Nullable<System.DateTime> value);
    partial void OnDataDateChanged();
    partial void OnHotelCodeChanging(string value);
    partial void OnHotelCodeChanged();
    partial void OnalldataChanging(System.Nullable<int> value);
    partial void OnalldataChanged();
    partial void OnHv_emailChanging(System.Nullable<int> value);
    partial void OnHv_emailChanged();
    partial void OnNot_emailChanging(System.Nullable<int> value);
    partial void OnNot_emailChanged();
    partial void OnHv_add1Changing(System.Nullable<int> value);
    partial void OnHv_add1Changed();
    partial void OnMedalliaChanging(System.Nullable<System.DateTime> value);
    partial void OnMedalliaChanged();
    #endregion
		
		public tbdata_medallia()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataID", DbType="SmallInt NOT NULL", IsPrimaryKey=true)]
		public short DataID
		{
			get
			{
				return this._DataID;
			}
			set
			{
				if ((this._DataID != value))
				{
					this.OnDataIDChanging(value);
					this.SendPropertyChanging();
					this._DataID = value;
					this.SendPropertyChanged("DataID");
					this.OnDataIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DataDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> DataDate
		{
			get
			{
				return this._DataDate;
			}
			set
			{
				if ((this._DataDate != value))
				{
					this.OnDataDateChanging(value);
					this.SendPropertyChanging();
					this._DataDate = value;
					this.SendPropertyChanged("DataDate");
					this.OnDataDateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HotelCode", DbType="VarChar(50)")]
		public string HotelCode
		{
			get
			{
				return this._HotelCode;
			}
			set
			{
				if ((this._HotelCode != value))
				{
					this.OnHotelCodeChanging(value);
					this.SendPropertyChanging();
					this._HotelCode = value;
					this.SendPropertyChanged("HotelCode");
					this.OnHotelCodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_alldata", DbType="Int")]
		public System.Nullable<int> alldata
		{
			get
			{
				return this._alldata;
			}
			set
			{
				if ((this._alldata != value))
				{
					this.OnalldataChanging(value);
					this.SendPropertyChanging();
					this._alldata = value;
					this.SendPropertyChanged("alldata");
					this.OnalldataChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hv_email", DbType="Int")]
		public System.Nullable<int> Hv_email
		{
			get
			{
				return this._Hv_email;
			}
			set
			{
				if ((this._Hv_email != value))
				{
					this.OnHv_emailChanging(value);
					this.SendPropertyChanging();
					this._Hv_email = value;
					this.SendPropertyChanged("Hv_email");
					this.OnHv_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Not_email", DbType="Int")]
		public System.Nullable<int> Not_email
		{
			get
			{
				return this._Not_email;
			}
			set
			{
				if ((this._Not_email != value))
				{
					this.OnNot_emailChanging(value);
					this.SendPropertyChanging();
					this._Not_email = value;
					this.SendPropertyChanged("Not_email");
					this.OnNot_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hv_add1", DbType="Int")]
		public System.Nullable<int> Hv_add1
		{
			get
			{
				return this._Hv_add1;
			}
			set
			{
				if ((this._Hv_add1 != value))
				{
					this.OnHv_add1Changing(value);
					this.SendPropertyChanging();
					this._Hv_add1 = value;
					this.SendPropertyChanged("Hv_add1");
					this.OnHv_add1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Medallia", DbType="DateTime")]
		public System.Nullable<System.DateTime> Medallia
		{
			get
			{
				return this._Medallia;
			}
			set
			{
				if ((this._Medallia != value))
				{
					this.OnMedalliaChanging(value);
					this.SendPropertyChanging();
					this._Medallia = value;
					this.SendPropertyChanged("Medallia");
					this.OnMedalliaChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TBDAT")]
	public partial class TBDAT : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _MedalID;
		
		private string _PROPERTYCODE;
		
		private string _ROOMNUMBER;
		
		private string _TITLE;
		
		private string _GUESTLASTNAME;
		
		private string _GUESTFIRSTNAME;
		
		private System.Nullable<System.DateTime> _CHECKINDATE;
		
		private System.Nullable<System.DateTime> _CHECKOUTDATE;
		
		private string _EMAIL;
		
		private string _ADDRESS;
		
		private string _ADDRESS2;
		
		private string _ADDRESS3;
		
		private string _ADDRESS4;
		
		private string _POST_CODE;
		
		private string _STATE;
		
		private string _ADDRESS_TYPE;
		
		private string _CITY;
		
		private string _COUNTRY;
		
		private string _ROOMRATE;
		
		private string _RESERVATIONNO;
		
		private string _ROOMTYPE;
		
		private string _RATECODE;
		
		private string _RATEVALUE;
		
		private string _LOYALTYPROGRAMMENO;
		
		private string _LOYALTYPROGRAMMESTATUS;
		
		private string _CUSTOMERTYPE;
		
		private string _MARKETSEGMENTCODE;
		
		private string _SOURCECODE;
		
		private string _COMPANYNAME;
		
		private string _TOTALROOMREV;
		
		private string _TOTALF_BREV;
		
		private string _TOTALEXTRAREV;
		
		private string _TOTALREV;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMedalIDChanging(int value);
    partial void OnMedalIDChanged();
    partial void OnPROPERTYCODEChanging(string value);
    partial void OnPROPERTYCODEChanged();
    partial void OnROOMNUMBERChanging(string value);
    partial void OnROOMNUMBERChanged();
    partial void OnTITLEChanging(string value);
    partial void OnTITLEChanged();
    partial void OnGUESTLASTNAMEChanging(string value);
    partial void OnGUESTLASTNAMEChanged();
    partial void OnGUESTFIRSTNAMEChanging(string value);
    partial void OnGUESTFIRSTNAMEChanged();
    partial void OnCHECKINDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCHECKINDATEChanged();
    partial void OnCHECKOUTDATEChanging(System.Nullable<System.DateTime> value);
    partial void OnCHECKOUTDATEChanged();
    partial void OnEMAILChanging(string value);
    partial void OnEMAILChanged();
    partial void OnADDRESSChanging(string value);
    partial void OnADDRESSChanged();
    partial void OnADDRESS2Changing(string value);
    partial void OnADDRESS2Changed();
    partial void OnADDRESS3Changing(string value);
    partial void OnADDRESS3Changed();
    partial void OnADDRESS4Changing(string value);
    partial void OnADDRESS4Changed();
    partial void OnPOST_CODEChanging(string value);
    partial void OnPOST_CODEChanged();
    partial void OnSTATEChanging(string value);
    partial void OnSTATEChanged();
    partial void OnADDRESS_TYPEChanging(string value);
    partial void OnADDRESS_TYPEChanged();
    partial void OnCITYChanging(string value);
    partial void OnCITYChanged();
    partial void OnCOUNTRYChanging(string value);
    partial void OnCOUNTRYChanged();
    partial void OnROOMRATEChanging(string value);
    partial void OnROOMRATEChanged();
    partial void OnRESERVATIONNOChanging(string value);
    partial void OnRESERVATIONNOChanged();
    partial void OnROOMTYPEChanging(string value);
    partial void OnROOMTYPEChanged();
    partial void OnRATECODEChanging(string value);
    partial void OnRATECODEChanged();
    partial void OnRATEVALUEChanging(string value);
    partial void OnRATEVALUEChanged();
    partial void OnLOYALTYPROGRAMMENOChanging(string value);
    partial void OnLOYALTYPROGRAMMENOChanged();
    partial void OnLOYALTYPROGRAMMESTATUSChanging(string value);
    partial void OnLOYALTYPROGRAMMESTATUSChanged();
    partial void OnCUSTOMERTYPEChanging(string value);
    partial void OnCUSTOMERTYPEChanged();
    partial void OnMARKETSEGMENTCODEChanging(string value);
    partial void OnMARKETSEGMENTCODEChanged();
    partial void OnSOURCECODEChanging(string value);
    partial void OnSOURCECODEChanged();
    partial void OnCOMPANYNAMEChanging(string value);
    partial void OnCOMPANYNAMEChanged();
    partial void OnTOTALROOMREVChanging(string value);
    partial void OnTOTALROOMREVChanged();
    partial void OnTOTALF_BREVChanging(string value);
    partial void OnTOTALF_BREVChanged();
    partial void OnTOTALEXTRAREVChanging(string value);
    partial void OnTOTALEXTRAREVChanged();
    partial void OnTOTALREVChanging(string value);
    partial void OnTOTALREVChanged();
    #endregion
		
		public TBDAT()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MedalID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int MedalID
		{
			get
			{
				return this._MedalID;
			}
			set
			{
				if ((this._MedalID != value))
				{
					this.OnMedalIDChanging(value);
					this.SendPropertyChanging();
					this._MedalID = value;
					this.SendPropertyChanged("MedalID");
					this.OnMedalIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PROPERTYCODE", DbType="VarChar(50)")]
		public string PROPERTYCODE
		{
			get
			{
				return this._PROPERTYCODE;
			}
			set
			{
				if ((this._PROPERTYCODE != value))
				{
					this.OnPROPERTYCODEChanging(value);
					this.SendPropertyChanging();
					this._PROPERTYCODE = value;
					this.SendPropertyChanged("PROPERTYCODE");
					this.OnPROPERTYCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOMNUMBER", DbType="VarChar(50)")]
		public string ROOMNUMBER
		{
			get
			{
				return this._ROOMNUMBER;
			}
			set
			{
				if ((this._ROOMNUMBER != value))
				{
					this.OnROOMNUMBERChanging(value);
					this.SendPropertyChanging();
					this._ROOMNUMBER = value;
					this.SendPropertyChanged("ROOMNUMBER");
					this.OnROOMNUMBERChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TITLE", DbType="VarChar(50)")]
		public string TITLE
		{
			get
			{
				return this._TITLE;
			}
			set
			{
				if ((this._TITLE != value))
				{
					this.OnTITLEChanging(value);
					this.SendPropertyChanging();
					this._TITLE = value;
					this.SendPropertyChanged("TITLE");
					this.OnTITLEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUESTLASTNAME", DbType="VarChar(50)")]
		public string GUESTLASTNAME
		{
			get
			{
				return this._GUESTLASTNAME;
			}
			set
			{
				if ((this._GUESTLASTNAME != value))
				{
					this.OnGUESTLASTNAMEChanging(value);
					this.SendPropertyChanging();
					this._GUESTLASTNAME = value;
					this.SendPropertyChanged("GUESTLASTNAME");
					this.OnGUESTLASTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GUESTFIRSTNAME", DbType="VarChar(50)")]
		public string GUESTFIRSTNAME
		{
			get
			{
				return this._GUESTFIRSTNAME;
			}
			set
			{
				if ((this._GUESTFIRSTNAME != value))
				{
					this.OnGUESTFIRSTNAMEChanging(value);
					this.SendPropertyChanging();
					this._GUESTFIRSTNAME = value;
					this.SendPropertyChanged("GUESTFIRSTNAME");
					this.OnGUESTFIRSTNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECKINDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CHECKINDATE
		{
			get
			{
				return this._CHECKINDATE;
			}
			set
			{
				if ((this._CHECKINDATE != value))
				{
					this.OnCHECKINDATEChanging(value);
					this.SendPropertyChanging();
					this._CHECKINDATE = value;
					this.SendPropertyChanged("CHECKINDATE");
					this.OnCHECKINDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHECKOUTDATE", DbType="DateTime")]
		public System.Nullable<System.DateTime> CHECKOUTDATE
		{
			get
			{
				return this._CHECKOUTDATE;
			}
			set
			{
				if ((this._CHECKOUTDATE != value))
				{
					this.OnCHECKOUTDATEChanging(value);
					this.SendPropertyChanging();
					this._CHECKOUTDATE = value;
					this.SendPropertyChanged("CHECKOUTDATE");
					this.OnCHECKOUTDATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EMAIL", DbType="VarChar(100)")]
		public string EMAIL
		{
			get
			{
				return this._EMAIL;
			}
			set
			{
				if ((this._EMAIL != value))
				{
					this.OnEMAILChanging(value);
					this.SendPropertyChanging();
					this._EMAIL = value;
					this.SendPropertyChanged("EMAIL");
					this.OnEMAILChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS", DbType="VarChar(100)")]
		public string ADDRESS
		{
			get
			{
				return this._ADDRESS;
			}
			set
			{
				if ((this._ADDRESS != value))
				{
					this.OnADDRESSChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS = value;
					this.SendPropertyChanged("ADDRESS");
					this.OnADDRESSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS2", DbType="VarChar(100)")]
		public string ADDRESS2
		{
			get
			{
				return this._ADDRESS2;
			}
			set
			{
				if ((this._ADDRESS2 != value))
				{
					this.OnADDRESS2Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS2 = value;
					this.SendPropertyChanged("ADDRESS2");
					this.OnADDRESS2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS3", DbType="VarChar(100)")]
		public string ADDRESS3
		{
			get
			{
				return this._ADDRESS3;
			}
			set
			{
				if ((this._ADDRESS3 != value))
				{
					this.OnADDRESS3Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS3 = value;
					this.SendPropertyChanged("ADDRESS3");
					this.OnADDRESS3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS4", DbType="VarChar(100)")]
		public string ADDRESS4
		{
			get
			{
				return this._ADDRESS4;
			}
			set
			{
				if ((this._ADDRESS4 != value))
				{
					this.OnADDRESS4Changing(value);
					this.SendPropertyChanging();
					this._ADDRESS4 = value;
					this.SendPropertyChanged("ADDRESS4");
					this.OnADDRESS4Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_POST_CODE", DbType="VarChar(50)")]
		public string POST_CODE
		{
			get
			{
				return this._POST_CODE;
			}
			set
			{
				if ((this._POST_CODE != value))
				{
					this.OnPOST_CODEChanging(value);
					this.SendPropertyChanging();
					this._POST_CODE = value;
					this.SendPropertyChanged("POST_CODE");
					this.OnPOST_CODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STATE", DbType="VarChar(50)")]
		public string STATE
		{
			get
			{
				return this._STATE;
			}
			set
			{
				if ((this._STATE != value))
				{
					this.OnSTATEChanging(value);
					this.SendPropertyChanging();
					this._STATE = value;
					this.SendPropertyChanged("STATE");
					this.OnSTATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ADDRESS_TYPE", DbType="VarChar(50)")]
		public string ADDRESS_TYPE
		{
			get
			{
				return this._ADDRESS_TYPE;
			}
			set
			{
				if ((this._ADDRESS_TYPE != value))
				{
					this.OnADDRESS_TYPEChanging(value);
					this.SendPropertyChanging();
					this._ADDRESS_TYPE = value;
					this.SendPropertyChanged("ADDRESS_TYPE");
					this.OnADDRESS_TYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CITY", DbType="VarChar(50)")]
		public string CITY
		{
			get
			{
				return this._CITY;
			}
			set
			{
				if ((this._CITY != value))
				{
					this.OnCITYChanging(value);
					this.SendPropertyChanging();
					this._CITY = value;
					this.SendPropertyChanged("CITY");
					this.OnCITYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COUNTRY", DbType="VarChar(50)")]
		public string COUNTRY
		{
			get
			{
				return this._COUNTRY;
			}
			set
			{
				if ((this._COUNTRY != value))
				{
					this.OnCOUNTRYChanging(value);
					this.SendPropertyChanging();
					this._COUNTRY = value;
					this.SendPropertyChanged("COUNTRY");
					this.OnCOUNTRYChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOMRATE", DbType="VarChar(50)")]
		public string ROOMRATE
		{
			get
			{
				return this._ROOMRATE;
			}
			set
			{
				if ((this._ROOMRATE != value))
				{
					this.OnROOMRATEChanging(value);
					this.SendPropertyChanging();
					this._ROOMRATE = value;
					this.SendPropertyChanged("ROOMRATE");
					this.OnROOMRATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESERVATIONNO", DbType="VarChar(50)")]
		public string RESERVATIONNO
		{
			get
			{
				return this._RESERVATIONNO;
			}
			set
			{
				if ((this._RESERVATIONNO != value))
				{
					this.OnRESERVATIONNOChanging(value);
					this.SendPropertyChanging();
					this._RESERVATIONNO = value;
					this.SendPropertyChanged("RESERVATIONNO");
					this.OnRESERVATIONNOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ROOMTYPE", DbType="VarChar(50)")]
		public string ROOMTYPE
		{
			get
			{
				return this._ROOMTYPE;
			}
			set
			{
				if ((this._ROOMTYPE != value))
				{
					this.OnROOMTYPEChanging(value);
					this.SendPropertyChanging();
					this._ROOMTYPE = value;
					this.SendPropertyChanged("ROOMTYPE");
					this.OnROOMTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RATECODE", DbType="VarChar(50)")]
		public string RATECODE
		{
			get
			{
				return this._RATECODE;
			}
			set
			{
				if ((this._RATECODE != value))
				{
					this.OnRATECODEChanging(value);
					this.SendPropertyChanging();
					this._RATECODE = value;
					this.SendPropertyChanged("RATECODE");
					this.OnRATECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RATEVALUE", DbType="VarChar(50)")]
		public string RATEVALUE
		{
			get
			{
				return this._RATEVALUE;
			}
			set
			{
				if ((this._RATEVALUE != value))
				{
					this.OnRATEVALUEChanging(value);
					this.SendPropertyChanging();
					this._RATEVALUE = value;
					this.SendPropertyChanged("RATEVALUE");
					this.OnRATEVALUEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOYALTYPROGRAMMENO", DbType="VarChar(50)")]
		public string LOYALTYPROGRAMMENO
		{
			get
			{
				return this._LOYALTYPROGRAMMENO;
			}
			set
			{
				if ((this._LOYALTYPROGRAMMENO != value))
				{
					this.OnLOYALTYPROGRAMMENOChanging(value);
					this.SendPropertyChanging();
					this._LOYALTYPROGRAMMENO = value;
					this.SendPropertyChanged("LOYALTYPROGRAMMENO");
					this.OnLOYALTYPROGRAMMENOChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOYALTYPROGRAMMESTATUS", DbType="VarChar(50)")]
		public string LOYALTYPROGRAMMESTATUS
		{
			get
			{
				return this._LOYALTYPROGRAMMESTATUS;
			}
			set
			{
				if ((this._LOYALTYPROGRAMMESTATUS != value))
				{
					this.OnLOYALTYPROGRAMMESTATUSChanging(value);
					this.SendPropertyChanging();
					this._LOYALTYPROGRAMMESTATUS = value;
					this.SendPropertyChanged("LOYALTYPROGRAMMESTATUS");
					this.OnLOYALTYPROGRAMMESTATUSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CUSTOMERTYPE", DbType="VarChar(50)")]
		public string CUSTOMERTYPE
		{
			get
			{
				return this._CUSTOMERTYPE;
			}
			set
			{
				if ((this._CUSTOMERTYPE != value))
				{
					this.OnCUSTOMERTYPEChanging(value);
					this.SendPropertyChanging();
					this._CUSTOMERTYPE = value;
					this.SendPropertyChanged("CUSTOMERTYPE");
					this.OnCUSTOMERTYPEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MARKETSEGMENTCODE", DbType="VarChar(50)")]
		public string MARKETSEGMENTCODE
		{
			get
			{
				return this._MARKETSEGMENTCODE;
			}
			set
			{
				if ((this._MARKETSEGMENTCODE != value))
				{
					this.OnMARKETSEGMENTCODEChanging(value);
					this.SendPropertyChanging();
					this._MARKETSEGMENTCODE = value;
					this.SendPropertyChanged("MARKETSEGMENTCODE");
					this.OnMARKETSEGMENTCODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SOURCECODE", DbType="VarChar(50)")]
		public string SOURCECODE
		{
			get
			{
				return this._SOURCECODE;
			}
			set
			{
				if ((this._SOURCECODE != value))
				{
					this.OnSOURCECODEChanging(value);
					this.SendPropertyChanging();
					this._SOURCECODE = value;
					this.SendPropertyChanged("SOURCECODE");
					this.OnSOURCECODEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_COMPANYNAME", DbType="VarChar(100)")]
		public string COMPANYNAME
		{
			get
			{
				return this._COMPANYNAME;
			}
			set
			{
				if ((this._COMPANYNAME != value))
				{
					this.OnCOMPANYNAMEChanging(value);
					this.SendPropertyChanging();
					this._COMPANYNAME = value;
					this.SendPropertyChanged("COMPANYNAME");
					this.OnCOMPANYNAMEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALROOMREV", DbType="VarChar(50)")]
		public string TOTALROOMREV
		{
			get
			{
				return this._TOTALROOMREV;
			}
			set
			{
				if ((this._TOTALROOMREV != value))
				{
					this.OnTOTALROOMREVChanging(value);
					this.SendPropertyChanging();
					this._TOTALROOMREV = value;
					this.SendPropertyChanged("TOTALROOMREV");
					this.OnTOTALROOMREVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALF_BREV", DbType="VarChar(50)")]
		public string TOTALF_BREV
		{
			get
			{
				return this._TOTALF_BREV;
			}
			set
			{
				if ((this._TOTALF_BREV != value))
				{
					this.OnTOTALF_BREVChanging(value);
					this.SendPropertyChanging();
					this._TOTALF_BREV = value;
					this.SendPropertyChanged("TOTALF_BREV");
					this.OnTOTALF_BREVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALEXTRAREV", DbType="VarChar(50)")]
		public string TOTALEXTRAREV
		{
			get
			{
				return this._TOTALEXTRAREV;
			}
			set
			{
				if ((this._TOTALEXTRAREV != value))
				{
					this.OnTOTALEXTRAREVChanging(value);
					this.SendPropertyChanging();
					this._TOTALEXTRAREV = value;
					this.SendPropertyChanged("TOTALEXTRAREV");
					this.OnTOTALEXTRAREVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTALREV", DbType="VarChar(50)")]
		public string TOTALREV
		{
			get
			{
				return this._TOTALREV;
			}
			set
			{
				if ((this._TOTALREV != value))
				{
					this.OnTOTALREVChanging(value);
					this.SendPropertyChanging();
					this._TOTALREV = value;
					this.SendPropertyChanged("TOTALREV");
					this.OnTOTALREVChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tbISO")]
	public partial class tbISO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _CountryID;
		
		private string _CountryName;
		
		private string _ISO3;
		
		private string _ISO2;
		
		private string _AAB;
		
		private string _ABB;
		
		private string _ACP;
		
		private string _AOP;
		
		private string _AEC;
		
		private string _APS;
		
		private string _ARC;
		
		private string _AVK;
		
		private string _AWB;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryIDChanging(byte value);
    partial void OnCountryIDChanged();
    partial void OnCountryNameChanging(string value);
    partial void OnCountryNameChanged();
    partial void OnISO3Changing(string value);
    partial void OnISO3Changed();
    partial void OnISO2Changing(string value);
    partial void OnISO2Changed();
    partial void OnAABChanging(string value);
    partial void OnAABChanged();
    partial void OnABBChanging(string value);
    partial void OnABBChanged();
    partial void OnACPChanging(string value);
    partial void OnACPChanged();
    partial void OnAOPChanging(string value);
    partial void OnAOPChanged();
    partial void OnAECChanging(string value);
    partial void OnAECChanged();
    partial void OnAPSChanging(string value);
    partial void OnAPSChanged();
    partial void OnARCChanging(string value);
    partial void OnARCChanged();
    partial void OnAVKChanging(string value);
    partial void OnAVKChanged();
    partial void OnAWBChanging(string value);
    partial void OnAWBChanged();
    #endregion
		
		public tbISO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryID", DbType="TinyInt NOT NULL", IsPrimaryKey=true)]
		public byte CountryID
		{
			get
			{
				return this._CountryID;
			}
			set
			{
				if ((this._CountryID != value))
				{
					this.OnCountryIDChanging(value);
					this.SendPropertyChanging();
					this._CountryID = value;
					this.SendPropertyChanged("CountryID");
					this.OnCountryIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CountryName", DbType="VarChar(150)")]
		public string CountryName
		{
			get
			{
				return this._CountryName;
			}
			set
			{
				if ((this._CountryName != value))
				{
					this.OnCountryNameChanging(value);
					this.SendPropertyChanging();
					this._CountryName = value;
					this.SendPropertyChanged("CountryName");
					this.OnCountryNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISO3", DbType="VarChar(3)")]
		public string ISO3
		{
			get
			{
				return this._ISO3;
			}
			set
			{
				if ((this._ISO3 != value))
				{
					this.OnISO3Changing(value);
					this.SendPropertyChanging();
					this._ISO3 = value;
					this.SendPropertyChanged("ISO3");
					this.OnISO3Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ISO2", DbType="VarChar(2)")]
		public string ISO2
		{
			get
			{
				return this._ISO2;
			}
			set
			{
				if ((this._ISO2 != value))
				{
					this.OnISO2Changing(value);
					this.SendPropertyChanging();
					this._ISO2 = value;
					this.SendPropertyChanged("ISO2");
					this.OnISO2Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AAB", DbType="VarChar(3)")]
		public string AAB
		{
			get
			{
				return this._AAB;
			}
			set
			{
				if ((this._AAB != value))
				{
					this.OnAABChanging(value);
					this.SendPropertyChanging();
					this._AAB = value;
					this.SendPropertyChanged("AAB");
					this.OnAABChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ABB", DbType="VarChar(3)")]
		public string ABB
		{
			get
			{
				return this._ABB;
			}
			set
			{
				if ((this._ABB != value))
				{
					this.OnABBChanging(value);
					this.SendPropertyChanging();
					this._ABB = value;
					this.SendPropertyChanged("ABB");
					this.OnABBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ACP", DbType="VarChar(3)")]
		public string ACP
		{
			get
			{
				return this._ACP;
			}
			set
			{
				if ((this._ACP != value))
				{
					this.OnACPChanging(value);
					this.SendPropertyChanging();
					this._ACP = value;
					this.SendPropertyChanged("ACP");
					this.OnACPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AOP", DbType="VarChar(3)")]
		public string AOP
		{
			get
			{
				return this._AOP;
			}
			set
			{
				if ((this._AOP != value))
				{
					this.OnAOPChanging(value);
					this.SendPropertyChanging();
					this._AOP = value;
					this.SendPropertyChanged("AOP");
					this.OnAOPChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AEC", DbType="VarChar(3)")]
		public string AEC
		{
			get
			{
				return this._AEC;
			}
			set
			{
				if ((this._AEC != value))
				{
					this.OnAECChanging(value);
					this.SendPropertyChanging();
					this._AEC = value;
					this.SendPropertyChanged("AEC");
					this.OnAECChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_APS", DbType="VarChar(3)")]
		public string APS
		{
			get
			{
				return this._APS;
			}
			set
			{
				if ((this._APS != value))
				{
					this.OnAPSChanging(value);
					this.SendPropertyChanging();
					this._APS = value;
					this.SendPropertyChanged("APS");
					this.OnAPSChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ARC", DbType="VarChar(3)")]
		public string ARC
		{
			get
			{
				return this._ARC;
			}
			set
			{
				if ((this._ARC != value))
				{
					this.OnARCChanging(value);
					this.SendPropertyChanging();
					this._ARC = value;
					this.SendPropertyChanged("ARC");
					this.OnARCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AVK", DbType="VarChar(3)")]
		public string AVK
		{
			get
			{
				return this._AVK;
			}
			set
			{
				if ((this._AVK != value))
				{
					this.OnAVKChanging(value);
					this.SendPropertyChanging();
					this._AVK = value;
					this.SendPropertyChanged("AVK");
					this.OnAVKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AWB", DbType="VarChar(3)")]
		public string AWB
		{
			get
			{
				return this._AWB;
			}
			set
			{
				if ((this._AWB != value))
				{
					this.OnAWBChanging(value);
					this.SendPropertyChanging();
					this._AWB = value;
					this.SendPropertyChanged("AWB");
					this.OnAWBChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
